services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      #Pamiętaj by dodać foldery!
    ports:
      - 1883:1883
      - 9001:9001
    stdin_open: true 
    tty: true
#https://pimylifeup.com/mosquitto-mqtt-docker/
#docker compose exec mosquitto sh
#mosquitto_passwd -c /mosquitto/config/pwfile <USERNAME>
